"""empty message

Revision ID: 7426c11def6f
Revises: 
Create Date: 2018-10-12 15:32:49.410801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7426c11def6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GaodeMapScene',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('city_adcode', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('longtitude', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('typecode', sa.String(length=20), nullable=True),
    sa.Column('classify', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('shape', sa.Text(), nullable=True),
    sa.Column('wgs_long', sa.Float(), nullable=True),
    sa.Column('wgs_lat', sa.Float(), nullable=True),
    sa.Column('wgs_shape', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adcode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('adcode', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenecode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('scenecode', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('city_adcode', sa.String(length=6), nullable=False),
    sa.Column('scene', sa.String(length=50), nullable=False),
    sa.Column('type_code', sa.String(length=6), nullable=False),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('final_grid', sa.Integer(), nullable=True),
    sa.Column('adsl_server_url', sa.String(length=100), nullable=False),
    sa.Column('adsl_auth', sa.String(length=100), nullable=False),
    sa.Column('keys', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('city_adcode', 'type_code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('is_activate', sa.Boolean(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_create_time'), 'note', ['create_time'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_create_time'), 'comment', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_create_time'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_note_create_time'), table_name='note')
    op.drop_table('note')
    op.drop_table('user')
    op.drop_table('scrape_missions')
    op.drop_table('scenecode')
    op.drop_table('adcode')
    op.drop_table('GaodeMapScene')
    # ### end Alembic commands ###
