"""empty message

Revision ID: a3e5feb1e136
Revises: 7426c11def6f
Create Date: 2018-10-15 10:27:39.994000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3e5feb1e136'
down_revision = '7426c11def6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GaodeMapScene',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('city_adcode', sa.String(length=20), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('longtitude', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('typecode', sa.String(length=20), nullable=True),
    sa.Column('classify', sa.String(length=100), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('shape', sa.Text(), nullable=True),
    sa.Column('wgs_long', sa.Float(), nullable=True),
    sa.Column('wgs_lat', sa.Float(), nullable=True),
    sa.Column('wgs_shape', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gaodemapscene')
    op.add_column('adcode', sa.Column('province', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adcode', 'province')
    op.create_table('gaodemapscene',
    sa.Column('id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('province', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('city_adcode', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('district', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('longtitude', mysql.FLOAT(), nullable=True),
    sa.Column('lat', mysql.FLOAT(), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('typecode', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('classify', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('area', mysql.FLOAT(), nullable=True),
    sa.Column('shape', mysql.TEXT(), nullable=True),
    sa.Column('wgs_long', mysql.FLOAT(), nullable=True),
    sa.Column('wgs_lat', mysql.FLOAT(), nullable=True),
    sa.Column('wgs_shape', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('GaodeMapScene')
    # ### end Alembic commands ###
